[build]
  command = "hugo --gc --minify -b https://n9o.xyz"
  publish = "public"

[build.environment]
HUGO_VERSION = "0.159.1"
HUGO_THEMESDIR = "themes"
HUGO_THEME = "blowfish"

[context.deploy-preview]
  command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"
